# Generated by Django 4.1 on 2023-01-12 06:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=400, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('author', models.CharField(max_length=250)),
                ('url', models.URLField(unique=True)),
                ('url_video', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('public_day', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='stories/image/logo.jpg', upload_to='stories/images')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stories.category')),
            ],
        ),
    ]
